

CREATE TABLE EMPLOYMENT_DETAILS(
ID INT NOT NULL IDENTITY,
PROFILE_ID INT NOT NULL,
LATEST_EMPLOYER VARCHAR(255),
OFFICIAL_MAIL_ID VARCHAR(255),
YRS_EXPERIENCE INT,
OCCUPATIONAL_CATEGORY VARCHAR(255),
PRIMARY KEY(ID),
FOREIGN KEY(PROFILE_ID) REFERENCES PROFILES(PROFILE_ID)
);


SELECT * FROM EMPLOYMENT_DETAILS

INSERT INTO EMPLOYMENT_DETAILS(PROFILE_ID ,LATEST_EMPLOYER,OFFICIAL_MAIL_ID,YRS_EXPERIENCE,OCCUPATIONAL_CATEGORY)
values(10,'huawei Technologies','gunjan19wadhwa@gmail.com',4,'Working')
INSERT INTO EMPLOYMENT_DETAILS(PROFILE_ID ,LATEST_EMPLOYER,OFFICIAL_MAIL_ID,YRS_EXPERIENCE,OCCUPATIONAL_CATEGORY)
values(11,'','',NULL,'Student');
INSERT INTO EMPLOYMENT_DETAILS(PROFILE_ID ,LATEST_EMPLOYER,OFFICIAL_MAIL_ID,YRS_EXPERIENCE,OCCUPATIONAL_CATEGORY)
values(12,'Centurylink India','PreetInder.Sodhi@centurylink.com',2,'Working');
INSERT INTO EMPLOYMENT_DETAILS(PROFILE_ID ,LATEST_EMPLOYER,OFFICIAL_MAIL_ID,YRS_EXPERIENCE,OCCUPATIONAL_CATEGORY)
values(13,'SAP Labs India','udit.singh@sap.com',2,'Working');
INSERT INTO EMPLOYMENT_DETAILS(PROFILE_ID ,LATEST_EMPLOYER,OFFICIAL_MAIL_ID,YRS_EXPERIENCE,OCCUPATIONAL_CATEGORY)
values(14,'NestAway','deepak@nestaway.com',1,'Working');
INSERT INTO EMPLOYMENT_DETAILS(PROFILE_ID ,LATEST_EMPLOYER,OFFICIAL_MAIL_ID,YRS_EXPERIENCE,OCCUPATIONAL_CATEGORY)
values(15,'','',NULL,'Student');
INSERT INTO EMPLOYMENT_DETAILS(PROFILE_ID ,LATEST_EMPLOYER,OFFICIAL_MAIL_ID,YRS_EXPERIENCE,OCCUPATIONAL_CATEGORY)
values(16,'','',NULL,'Student');
INSERT INTO EMPLOYMENT_DETAILS(PROFILE_ID ,LATEST_EMPLOYER,OFFICIAL_MAIL_ID,YRS_EXPERIENCE,OCCUPATIONAL_CATEGORY)
values(17,'Microsoft','t-akmeh@microsoft.com',2,'Working');
INSERT INTO EMPLOYMENT_DETAILS(PROFILE_ID ,LATEST_EMPLOYER,OFFICIAL_MAIL_ID,YRS_EXPERIENCE,OCCUPATIONAL_CATEGORY)
values(18,'Cognizant','bhavranjan.pandey@cognizant.com',2,'Working');
INSERT INTO EMPLOYMENT_DETAILS(PROFILE_ID ,LATEST_EMPLOYER,OFFICIAL_MAIL_ID,YRS_EXPERIENCE,OCCUPATIONAL_CATEGORY)
values(19,'','',NULL,'Student');
INSERT INTO EMPLOYMENT_DETAILS(PROFILE_ID ,LATEST_EMPLOYER,OFFICIAL_MAIL_ID,YRS_EXPERIENCE,OCCUPATIONAL_CATEGORY)
values(20,'Tiny Mogul Games','sanchit@hike.in',3,'Working');
values(9,'','',NULL,'Student');
values(7,'','',NULL,'Student');
values(8,'','',NULL,'Student');
values(6,'Aditya birla','shubhi.bajpai@adityabirla.com',3,'Working');
values(5,'GE Healthcare','ruchita.save@ge.com',3,'Working');
values(4,'','',NULL,'Student');
values(3,'Technicolor','jigna.thacker@technicolor.com',1,'Working');
values(2,'hindustan unilever','rags.ramgas@gmail.com',2,'Working');
values(1,'Sabre','mehdi.hasan@sabre.com',1,'Working');
