
CREATE TABLE PROFILES(
    PROFILE_ID INT NOT NULL IDENTITY,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    EMAIL VARCHAR(255) NOT NULL,
    PHONE VARCHAR(255) NOT NULL,
    CITY VARCHAR(255),
    PAN_CARD VARCHAR(255),
    CREATED_AT DATE NOT NULL,
    GENDER VARCHAR(255) NOT NULL,
    REFERRAL_CODE VARCHAR(255),
    MARTIAL_STATUS VARCHAR(255),
 PRIMARY KEY(PROFILE_ID)
);

INSERT INTO PROFILES(FIRST_NAME,LAST_NAME, EMAIL,PHONE ,CITY, PAN_CARD, CREATED_AT,GENDER ,REFERRAL_CODE,MARTIAL_STATUS)
VALUES 
('Karan','Singh','karan.singh@gmail.com','8976665768','Delhi','','9/15/2015','M','LRF34F','N');
INSERT INTO PROFILES(FIRST_NAME,LAST_NAME, EMAIL,PHONE ,CITY, PAN_CARD, CREATED_AT,GENDER ,REFERRAL_CODE,MARTIAL_STATUS)
VALUES
('Tanvi','mann','tanvi.mann1907@gmail.com','9178352769','Bangalore','','2/16/2015','F','JSH48B','N');
INSERT INTO PROFILES(FIRST_NAME,LAST_NAME, EMAIL,PHONE ,CITY, PAN_CARD, CREATED_AT,GENDER ,REFERRAL_CODE,MARTIAL_STATUS)
VALUES
('Ankita','sharma','ankita.anku96@gmail.com','9988789656','Delhi','','8/17/2015','F','TH67TY','Y');
INSERT INTO PROFILES(FIRST_NAME,LAST_NAME, EMAIL,PHONE ,CITY, PAN_CARD, CREATED_AT,GENDER ,REFERRAL_CODE,MARTIAL_STATUS)
VALUES
('Prabhjot','gill','prabhjotgill09@gmail.com','9800786688','Delhi','','12/30/2015','M','GHJK34','N');
INSERT INTO PROFILES(FIRST_NAME,LAST_NAME, EMAIL,PHONE ,CITY, PAN_CARD, CREATED_AT,GENDER ,REFERRAL_CODE,MARTIAL_STATUS)
VALUES
('Roosena','manuel','roseenasimimanuel@gmail.com','9875623345','Delhi','','4/13/2015','F','6TYHU','Y');
INSERT INTO PROFILES(FIRST_NAME,LAST_NAME, EMAIL,PHONE ,CITY, PAN_CARD, CREATED_AT,GENDER ,REFERRAL_CODE,MARTIAL_STATUS)
VALUES
('Rajan','pandey','raajanpandey@gmail.com','8987647811','delhi','','9/4/2015','M','5TYUIO','N');
INSERT INTO PROFILES(FIRST_NAME,LAST_NAME, EMAIL,PHONE ,CITY, PAN_CARD, CREATED_AT,GENDER ,REFERRAL_CODE,MARTIAL_STATUS)
VALUES
('Shivani','godha','shivani_go@nid.edu','9878673428','Delhi','','2/19/2015','F','8NM4R','Y');
INSERT INTO PROFILES(FIRST_NAME,LAST_NAME, EMAIL,PHONE ,CITY, PAN_CARD, CREATED_AT,GENDER ,REFERRAL_CODE,MARTIAL_STATUS)
VALUES
('Manisha','Yadav','maniyadav88@gmail.com','9867845182','Delhi','','1/27/2015','F','LKGHY6','N');
INSERT INTO PROFILES(FIRST_NAME,LAST_NAME, EMAIL,PHONE ,CITY, PAN_CARD, CREATED_AT,GENDER ,REFERRAL_CODE,MARTIAL_STATUS)
VALUES
('Mitali','gupta','mitali.gupta80@gmail.com','8796751238','Pune','','3/24/2015','F','5RTYU3','Y');
INSERT INTO PROFILES(FIRST_NAME,LAST_NAME, EMAIL,PHONE ,CITY, PAN_CARD, CREATED_AT,GENDER ,REFERRAL_CODE,MARTIAL_STATUS)
VALUES
('Umang','parejiya','uparejiya@gmail.com','7896543674','Pune','','7/18/2015','M','6TY4WE','N');
INSERT INTO PROFILES(FIRST_NAME,LAST_NAME, EMAIL,PHONE ,CITY, PAN_CARD, CREATED_AT,GENDER ,REFERRAL_CODE,MARTIAL_STATUS)
VALUES
('Deepa','sudhakar','sudhakar.deepa@gmail.com','7896785432','Pune','','9/15/2015','F','4RTYUIO','Y');
INSERT INTO PROFILES(FIRST_NAME,LAST_NAME, EMAIL,PHONE ,CITY, PAN_CARD, CREATED_AT,GENDER ,REFERRAL_CODE,MARTIAL_STATUS)
VALUES
('Aditi','jain','aditi.jain@sproxil.com','9873123456','Pune','','6/11/2015','F','5TPL4E','N');
INSERT INTO PROFILES(FIRST_NAME,LAST_NAME, EMAIL,PHONE ,CITY, PAN_CARD, CREATED_AT,GENDER ,REFERRAL_CODE,MARTIAL_STATUS)
VALUES
('Shivshankar','das','sankar.shiva730@gmail.com','9801834992','Pune','','10/6/2015','M','3RE5TY','Y');
INSERT INTO PROFILES(FIRST_NAME,LAST_NAME, EMAIL,PHONE ,CITY, PAN_CARD, CREATED_AT,GENDER ,REFERRAL_CODE,MARTIAL_STATUS)
VALUES
('Tushar','kapoor','tushar.kapoor21@gmail.com','8926537154','Pune','','12/12/2015','M','KLF12E','N');
INSERT INTO PROFILES(FIRST_NAME,LAST_NAME, EMAIL,PHONE ,CITY, PAN_CARD, CREATED_AT,GENDER ,REFERRAL_CODE,MARTIAL_STATUS)
VALUES
('Kamal','gera','kamal0094@gmail.com','8105987404','Bangalore','','10/31/2015','M','MK34ER','N');
INSERT INTO PROFILES(FIRST_NAME,LAST_NAME, EMAIL,PHONE ,CITY, PAN_CARD, CREATED_AT,GENDER ,REFERRAL_CODE,MARTIAL_STATUS)
VALUES
('Harish','sahai','harish294all@gmail.com','9876548763','Bangalore','','11/11/2015','M','MKGI2W','Y');
INSERT INTO PROFILES(FIRST_NAME,LAST_NAME, EMAIL,PHONE ,CITY, PAN_CARD, CREATED_AT,GENDER ,REFERRAL_CODE,MARTIAL_STATUS)
VALUES
('Bhaskar','maheshwari','bhaskar.mah@gmail.com','9801834992','Bangalore','','05/01/2015','M','5TYSHGF','N');
INSERT INTO PROFILES(FIRST_NAME,LAST_NAME, EMAIL,PHONE ,CITY, PAN_CARD, CREATED_AT,GENDER ,REFERRAL_CODE,MARTIAL_STATUS)
VALUES
('Ashish','	Singh',	'ashish.singh@gmail.com',	'9876890463',	'Bangalore','',	'05/23/2015',	'M',	'KF34MF',	'Y');
INSERT INTO PROFILES(FIRST_NAME,LAST_NAME, EMAIL,PHONE ,CITY, PAN_CARD, CREATED_AT,GENDER ,REFERRAL_CODE,MARTIAL_STATUS)
VALUES('anusha','pariti',	'anusha.pariti@gmail.com',	'8105987404',	'Bangalore','','	04/16/2015','	F','	7L5FZW','	Y');
INSERT INTO PROFILES(FIRST_NAME,LAST_NAME, EMAIL,PHONE ,CITY, PAN_CARD, CREATED_AT,GENDER ,REFERRAL_CODE,MARTIAL_STATUS)
VALUES('Garima','yadav','garima0191@gmail.com','81059237004','Bangalore','','10/20/2015','F','5G5FQW','N');
