CREATE TABLE TENANCY_HISTORIES(
    ID INT NOT NULL IDENTITY,
    PROFILE_ID INT NOT NULL,
    HOUSE_ID INT NOT NULL,
    MOVE_IN_DATE DATE NOT NULL,
    MOVE_OUT_DATE DATE,
    RENT INT NOT NULL,
    BED_TYPE VARCHAR(255),
    MOVE_OUT_REASON VARCHAR(255),
PRIMARY KEY (ID),
FOREIGN KEY(PROFILE_ID) REFERENCES PROFILES(PROFILE_ID),
FOREIGN KEY(HOUSE_ID) REFERENCES HOUSES(HOUSE_ID)
);


INSERT INTO TENANCY_HISTORIES(PROFILE_ID,HOUSE_ID, MOVE_IN_DATE, MOVE_OUT_DATE, RENT, BED_TYPE , MOVE_OUT_REASON)
values(1,5,'2/12/2015','4/30/2016',7500,'bed','MOVE_OUT');
INSERT INTO TENANCY_HISTORIES(PROFILE_ID,HOUSE_ID, MOVE_IN_DATE, MOVE_OUT_DATE, RENT, BED_TYPE , MOVE_OUT_REASON)
values(2,2,'6/5/2015',NULL,11000,'room','');
INSERT INTO TENANCY_HISTORIES(PROFILE_ID,HOUSE_ID, MOVE_IN_DATE, MOVE_OUT_DATE, RENT, BED_TYPE , MOVE_OUT_REASON)
values(3,4,'10/28/2015','11/28/2016',12000,'room','RENT_CHANGE');
INSERT INTO TENANCY_HISTORIES(PROFILE_ID,HOUSE_ID, MOVE_IN_DATE, MOVE_OUT_DATE, RENT, BED_TYPE , MOVE_OUT_REASON)
values(4,1,'4/26/2015',NULL,8000,'bed','');
INSERT INTO TENANCY_HISTORIES(PROFILE_ID,HOUSE_ID, MOVE_IN_DATE, MOVE_OUT_DATE, RENT, BED_TYPE , MOVE_OUT_REASON)
values(5,3,'5/15/2015','12/27/2015',9000,'bed','MOVE_OUT');
INSERT INTO TENANCY_HISTORIES(PROFILE_ID,HOUSE_ID, MOVE_IN_DATE, MOVE_OUT_DATE, RENT, BED_TYPE , MOVE_OUT_REASON)
values(6,8,'12/25/2015',NULL,10200,'room','');
INSERT INTO TENANCY_HISTORIES(PROFILE_ID,HOUSE_ID, MOVE_IN_DATE, MOVE_OUT_DATE, RENT, BED_TYPE , MOVE_OUT_REASON)
values(7,6,'11/20/2015',NULL,6500,'bed','');
INSERT INTO TENANCY_HISTORIES(PROFILE_ID,HOUSE_ID, MOVE_IN_DATE, MOVE_OUT_DATE, RENT, BED_TYPE , MOVE_OUT_REASON)
values(8,7,'11/10/2015','12/31/2016',7200,'bed','MOVE_OUT');
INSERT INTO TENANCY_HISTORIES(PROFILE_ID,HOUSE_ID, MOVE_IN_DATE, MOVE_OUT_DATE, RENT, BED_TYPE , MOVE_OUT_REASON)
values(9,9,'10/15/2015',NULL,7500,'bed','');
INSERT INTO TENANCY_HISTORIES(PROFILE_ID,HOUSE_ID, MOVE_IN_DATE, MOVE_OUT_DATE, RENT, BED_TYPE , MOVE_OUT_REASON)
values(10,10,'6/20/2015',NULL,7500,'bed','');
INSERT INTO TENANCY_HISTORIES(PROFILE_ID,HOUSE_ID, MOVE_IN_DATE, MOVE_OUT_DATE, RENT, BED_TYPE , MOVE_OUT_REASON)
values(11,19,'8/29/2015','6/14/2016',8000,'bed','INTERNAL_TRANSFER');
INSERT INTO TENANCY_HISTORIES(PROFILE_ID,HOUSE_ID, MOVE_IN_DATE, MOVE_OUT_DATE, RENT, BED_TYPE , MOVE_OUT_REASON)
values(12,15,'2/24/2015',NULL,11000,'room','');
INSERT INTO TENANCY_HISTORIES(PROFILE_ID,HOUSE_ID, MOVE_IN_DATE, MOVE_OUT_DATE, RENT, BED_TYPE , MOVE_OUT_REASON)
values(13,12,'2/25/2015',NULL,12000,'room','');
INSERT INTO TENANCY_HISTORIES(PROFILE_ID,HOUSE_ID, MOVE_IN_DATE, MOVE_OUT_DATE, RENT, BED_TYPE , MOVE_OUT_REASON)
values(14,18,'1/7/2016','12/30/2016',13500,'room','MOVE_OUT');
INSERT INTO TENANCY_HISTORIES(PROFILE_ID,HOUSE_ID, MOVE_IN_DATE, MOVE_OUT_DATE, RENT, BED_TYPE , MOVE_OUT_REASON)
values(15,13,'4/7/2015',NULL,6500,'bed','');
INSERT INTO TENANCY_HISTORIES(PROFILE_ID,HOUSE_ID, MOVE_IN_DATE, MOVE_OUT_DATE, RENT, BED_TYPE , MOVE_OUT_REASON)
values(16,17,'4/23/2015',NULL,6500,'bed','');
INSERT INTO TENANCY_HISTORIES(PROFILE_ID,HOUSE_ID, MOVE_IN_DATE, MOVE_OUT_DATE, RENT, BED_TYPE , MOVE_OUT_REASON)
values(17,14,'2/10/2015',NULL,10500,'room','');
INSERT INTO TENANCY_HISTORIES(PROFILE_ID,HOUSE_ID, MOVE_IN_DATE, MOVE_OUT_DATE, RENT, BED_TYPE , MOVE_OUT_REASON)
values(18,16,'10/16/2015','9/4/2016',8000,'bed','MOVE_OUT');
INSERT INTO TENANCY_HISTORIES(PROFILE_ID,HOUSE_ID, MOVE_IN_DATE, MOVE_OUT_DATE, RENT, BED_TYPE , MOVE_OUT_REASON)
values(19,20,'9/26/2015',NULL,7500,'bed','');
INSERT INTO TENANCY_HISTORIES(PROFILE_ID,HOUSE_ID, MOVE_IN_DATE, MOVE_OUT_DATE, RENT, BED_TYPE , MOVE_OUT_REASON)
values(20,11,'9/30/2015',NULL,9500,'bed','');