
1. SELECT TOP 1 TENANCY_HISTORIES.PROFILE_ID
	,first_name + ' ' + last_name AS Full_Name
	,phone
	,DATEDIFF(DAY, TENANCY_HISTORIES.MOVE_IN_DATE, TENANCY_HISTORIES.MOVE_OUT_DATE) AS Duration
FROM PROFILES
JOIN TENANCY_HISTORIES ON PROFILES.PROFILE_ID = TENANCY_HISTORIES.PROFILE_ID
ORDER BY Duration DESC;

